// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsIipcasfqmajUN5p2Dz2D2QMr0cAgHhA',
    appId: '1:1092735611218:web:8ed27ddbcae6479b770a8b',
    messagingSenderId: '1092735611218',
    projectId: 'bootcamp-db92b',
    authDomain: 'bootcamp-db92b.firebaseapp.com',
    storageBucket: 'bootcamp-db92b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5db_lnJk_YoGWec_-Hxj5COr9GwKwVak',
    appId: '1:1092735611218:android:19c62b48a8347bff770a8b',
    messagingSenderId: '1092735611218',
    projectId: 'bootcamp-db92b',
    storageBucket: 'bootcamp-db92b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6QDGsfKU_eEyVjiZJGOZy9D8JWn0aK_U',
    appId: '1:1092735611218:ios:084b2d15df625316770a8b',
    messagingSenderId: '1092735611218',
    projectId: 'bootcamp-db92b',
    storageBucket: 'bootcamp-db92b.firebasestorage.app',
    iosBundleId: 'com.example.gamingCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6QDGsfKU_eEyVjiZJGOZy9D8JWn0aK_U',
    appId: '1:1092735611218:ios:084b2d15df625316770a8b',
    messagingSenderId: '1092735611218',
    projectId: 'bootcamp-db92b',
    storageBucket: 'bootcamp-db92b.firebasestorage.app',
    iosBundleId: 'com.example.gamingCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsIipcasfqmajUN5p2Dz2D2QMr0cAgHhA',
    appId: '1:1092735611218:web:b990c926de129c7d770a8b',
    messagingSenderId: '1092735611218',
    projectId: 'bootcamp-db92b',
    authDomain: 'bootcamp-db92b.firebaseapp.com',
    storageBucket: 'bootcamp-db92b.firebasestorage.app',
  );
}
